python scripts/quadloco_rsl_rl/run_data_collection.py \
    --task Unitree-Go2-Quadloco-ManagerBased-Rough-DataCollection-v0 \
    --num_envs 1 \
    --checkpoint ckpt/model_999.pt \
    --dataset_format lerobot \
    --dataset_repo_id DinhQuangDung/quadloco-object-navigation \
    --num_episodes 1000 \
    --dataset_dir /home/summerschool/summerschool_ws/Dataset/quadloco-vla-lerobot_no_depth \
    --depth_width 128 \
    --depth_height 96 \
    --depth_scale 0.001 \
    --no-lerobot_include_depth \
    --collect_data \
    --headless \
    --push_to_hub
