from __future__ import annotations

from typing import TYPE_CHECKING

import os
import torch
import torch.nn.functional as F

from omni.isaac.lab.managers import SceneEntityCfg
from omni.isaac.lab.sensors import RayCaster
from omni.isaac.lab.sensors.camera import CameraData
from omni.isaac.lab.sensors.camera.utils import convert_orientation_convention
import omni.isaac.lab.utils.math as math_utils
from omni.isaac.lab.assets import Articulation, RigidObject

from .actions import NavigationAction, VLMActions, VLMActionsGPT
import matplotlib.pyplot as plt
import cv2

if TYPE_CHECKING:
    from omni.isaac.lab.envs.base_env import BaseEnv
    from omni.isaac.lab.envs import ManagerBasedEnv

def matterport_raycast_camera_data(env: BaseEnv, sensor_cfg: SceneEntityCfg, data_type: str) -> torch.Tensor:
    """Images generated by the raycast camera."""
    # extract the used quantities (to enable type-hinting)
    sensor: CameraData = env.scene.sensors[sensor_cfg.name].data

    # return the data
    if data_type == "distance_to_image_plane":
        output = sensor.output[data_type].clone().unsqueeze(1)
        output[torch.isnan(output)] = 0.0
        output[torch.isinf(output)] = 0.0
        return output
    else:
        return sensor.output[data_type].clone().permute(0, 3, 1, 2)

def isaac_camera_data(env: BaseEnv, sensor_cfg: SceneEntityCfg, data_type: str) -> torch.Tensor:
    """Images generated by the usd camera."""
    # extract the used quantities (to enable type-hinting)
    sensor: CameraData = env.scene.sensors[sensor_cfg.name].data

    # import ipdb; ipdb.set_trace()
    # return the data
    if data_type == "distance_to_image_plane":
        output = sensor.output[data_type].clone().unsqueeze(1)
        output[torch.isnan(output)] = 0.0
        output[torch.isinf(output)] = 0.0
        # output = torch.clip(output, 0.0, 10.0)
        # near_clip = 0.0
        # far_clip = 10.0
        # output = (output - near_clip) / (far_clip - near_clip)  - 0.5
        # depth_image_size = (output.shape[2], output.shape[3])
        # output_clone = output.clone().reshape(env.num_envs, depth_image_size[0], depth_image_size[1])[0,:,:]
        # window_name = "Depth Image"
        # cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
        # cv2.imshow("Depth Image", output_clone.cpu().numpy())
        # cv2.waitKey(1)
        return output
    else:
        # import ipdb; ipdb.set_trace()
        rgb_image = sensor.output[data_type].clone().cpu().numpy()[0,:,:,:]
        # # depth_image_size = (output.shape[2], output.shape[3])
        # output_clone = output.clone().reshape(env.num_envs, depth_image_size[0], depth_image_size[1])[0,:,:]
        # window_name = "RGB Image"
        # cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
        # cv2.imshow(window_name, rgb_image)
        # cv2.waitKey(1)
        return sensor.output[data_type].clone()

def process_depth_image(env: BaseEnv, sensor_cfg: SceneEntityCfg, data_type: str, visualize=False) -> torch.Tensor:
    """Process the depth image."""
    # import ipdb; ipdb.set_trace()
    # extract the used quantities (to enable type-hinting)
    sensor: CameraData = env.scene.sensors[sensor_cfg.name].data

    output = sensor.output[data_type].clone().unsqueeze(1)
    # # output = output[:,:, :-2, 4:-4]
    near_clip = 0.3
    far_clip = 2.0
    output[torch.isnan(output)] = far_clip
    output[torch.isinf(output)] = far_clip

    # depth_image_size = (output.shape[2], output.shape[3])
    # output_clone = output.clone().reshape(env.num_envs, depth_image_size[0], depth_image_size[1])[0,:,:]
    # window_name = "Before clipping"
    # import ipdb; ipdb.set_trace()
    # cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
    # cv2.imshow(window_name, output_clone.cpu().numpy())
    # cv2.waitKey(1)

    
    output = torch.clip(output, near_clip, far_clip)
    output = output - near_clip
    # output = F.interpolate(output, size=(53, 30), mode='nearest')
    # depth_image_size = (output.shape[2], output.shape[3])
    # output_clone = output.clone().reshape(env.num_envs, depth_image_size[0], depth_image_size[1])[0,:,:]
    # window_name = "after clipping and normalization"
    # cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
    # cv2.imshow(window_name, output_clone.cpu().numpy())
    # cv2.waitKey(1)


    # process_depth_feature = env.action_manager._terms['paths'].depth_cnn(output)
    # print("depth shape: ", output.reshape(env.num_envs, -1).shape)
    # import ipdb; ipdb.set_trace()
    # path = "/home/yji/Biped/biped_vision/depth_image/"
    # path=os.path.join(path, str(env.action_manager._terms['paths'].image_count)+".png")
    # import ipdb; ipdb.set_trace()
    if visualize:
        depth_image_size = (output.shape[2], output.shape[3])
        output_clone = output.clone().reshape(env.num_envs, depth_image_size[0], depth_image_size[1])[0,:,:]
        window_name = "Depth Image"
        cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
        cv2.imshow("Depth Image", output_clone.cpu().numpy())
        cv2.waitKey(1)

    # plt.imsave(path, output_clone.cpu().numpy(), cmap="gray")
    
    # print(output)
    return output.reshape(env.num_envs, -1)